DROP SCHEMA IF EXISTS registre;
CREATE SCHEMA registre;

USE registre;


CREATE TABLE IF NOT EXISTS `registre`.`usuari` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(63) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `dades` VARCHAR(255) ,
  `creat_date` DATETIME(1)  DEFAULT CURRENT_TIMESTAMP,
  `modificat_date` DATETIME(1) ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB;

